<Project Sdk="Aspire.AppHost.Sdk/13.2.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>75b77fd0-3c81-48f8-85b6-5744354afac4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nexo.Server\Nexo.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.2.4" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.2.4" />
  </ItemGroup>
</Project>
